### ISSUE TITLE
No module name from mmdt3d.core import LiDARInstance3DBoxes

### ISSUE THREAD

**Issue by ramnamaqsood** [aimotive/mm_training#2]
Hi,

I am facing an issue in this code that says 
 **from mmdt3d.core import LiDARInstance3DBoxes**
There is no module named core in mmdt3d repository and even there are few more modules that are not available. Also, i tried to install the previous version of mmdetection3D but by default only latest version get install. 
Can you please guide me in this regard. Thank you !!

**Comment by TamasMatuszka** [comment]
Hi @ramnamaqsood ,

Did you try MMDetection3D v1.0.0rc4?

I'm at the ICLR conference now and didn't bring a laptop with a developer environment. I can check the issue and help you to resolve the problem after the conference.

**Comment by ramnamaqsood** [comment]
Hi @TamasMatuszka 
Thank you very much for your response

Yes I am using mmdet3d v1.0.0rc4. 
Can you tell me which version of mmdet and mmcv has been used during the experiments?

**Comment by TamasMatuszka** [comment]
@ramnamaqsood, my colleague tested the repo by a clean installation using the following MMDetection3D v1.0.0rc4-related package version:
pip install -U openmim
mim install mmcv-full==1.7.0
mim install mmsegmentation==0.28.0
mim install mmdet==2.25.1
pip install mmdet3d==1.0.0.rc4
numpy==1.23.5
kornia==0.6.1

This setup worked for him; it should work for you too. In the meantime, we are updating the repository to work with newer versions of MMDetection3D.

**Comment by ramnamaqsood** [comment]
Hi @TamasMatuszka thank you very much for this information. Yes now problem is resolved.
And writing this just for others who will try to run this code "Don't install mmcv and mmdet with pip and cudatoolkit comands as it will always create conflicts with pytorch". In my case it only works with mim commands.
